### ISSUE TITLE
problema na notificação

### ISSUE THREAD

**Issue by jeffersonmello** [gabrielbarros/pagseguro#1]
na notificação e consulta está retornando este erro:

> Parse error: syntax error, unexpected '(' in C:\xampp\htdocs\painelnovo\shop\libs\pagseguro-master\src\PagSeguro\PagSeguroNotificacao.php on line 59

oque poderia ser ?

**Comment by gabrielbarros** [comment]
É que o trecho do código só era compatível com versões mais recentes do PHP. Acabei de atualizar o código.
